#!/bin/sh
REFERENCE_FILESYSTEM="/Devel/NOVAsom_SDK/FileSystem/P_Base"
ARMGCC="${REFERENCE_FILESYSTEM}/output/host/bin/arm-linux-g++ -std=gnu++11"
if ! [ -d ${REFERENCE_FILESYSTEM} ]; then
	echo "Please select an existing file system as base file system"
	exit -1
fi
if ! [ -f ../tools/iec2c ]; then
	cd matiec
	./configure
	make
	cp iec2c ../tools/.
	cd ..
fi

cd src
! [ -f ../tools/st_optimizer ] && g++ st_optimizer.cpp -o ../tools/st_optimizer
! [ -f ../tools/glue_generator ] && g++ glue_generator.cpp -o ../tools/glue_generator
cd ..

cd core
echo "Generating executable ... "
../tools/st_optimizer ../st/st_file.st ../st/out.st
../tools/iec2c -I ../lib ../st/out.st
ARCH=arm ${ARMGCC} -I ./lib -c Config0.c -lasiodnp3 -lasiopal -lopendnp3 -lopenpal
ARCH=arm ${ARMGCC} -I ./lib -c Res0.c -lasiodnp3 -lasiopal -lopendnp3 -lopenpal
../tools/glue_generator
ARCH=arm ${ARMGCC} *.cpp *.o -o ../novaplc -I./lib -lrt -lpthread -fpermissive
cd ..
ARCH=arm ${ARMGCC} writefifo.c -o  writefifo
